[pytest]
testpaths = tests
filterwarnings =
    ignore::DeprecationWarning:websockets
    ignore::DeprecationWarning:websockets.legacy
    ignore::DeprecationWarning:uvicorn.protocols.websockets.websockets_impl
